# -*- coding: utf-8 -*-
"""mlfinal_project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SCAcF5QDcHB8aEoTBAo1zTad9SZc7dpG
"""

from google.colab import files
files.upload()

from tensorflow.keras.models import load_model

model = load_model("waste_model.h5")

# =========================
# IMPORTS
# =========================
import tensorflow as tf
import numpy as np
from PIL import Image
from tensorflow.keras.models import load_model
from google.colab import files
import cv2
import base64
from IPython.display import display, HTML

# =========================
# SETTINGS
# =========================
IMG_SIZE = 224
MODEL_PATH = "waste_model.h5"

# =========================
# LOAD MODEL
# =========================
model = load_model(MODEL_PATH)

class_names = ['battery','biological','brown-glass','cardboard','clothes',
               'green-glass','metal','paper','plastic','shoes','trash','white-glass']

# =========================
# HEATMAP MODEL
# =========================
heatmap_model = tf.keras.applications.MobileNetV2(weights="imagenet")

# =========================
# HEATMAP FUNCTION
# =========================
def generate_heatmap(image_path):

    img = Image.open(image_path).convert("RGB").resize((224,224))
    img_array = np.array(img)
    img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)
    img_array = np.expand_dims(img_array, axis=0)

    last_conv_layer = heatmap_model.get_layer("Conv_1")

    grad_model = tf.keras.models.Model(
        [heatmap_model.inputs],
        [last_conv_layer.output, heatmap_model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        class_idx = tf.argmax(predictions[0])
        loss = predictions[:, class_idx]

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap).numpy()

    heatmap = np.maximum(heatmap, 0)
    if np.max(heatmap) != 0:
        heatmap /= np.max(heatmap)

    img = cv2.imread(image_path)
    img = cv2.resize(img, (224,224))

    heatmap = cv2.resize(heatmap, (224,224))
    heatmap = np.uint8(255 * heatmap)
    heatmap = cv2.applyColorMap(heatmap, cv2.COLORMAP_JET)

    superimposed_img = cv2.addWeighted(img, 0.6, heatmap, 0.4, 0)

    _, buffer = cv2.imencode('.jpg', superimposed_img)
    heatmap_src = base64.b64encode(buffer).decode()

    return f"data:image/jpeg;base64,{heatmap_src}"

# =========================
# MAIN FUNCTION
# =========================
def predict_waste(image_path):

    img = Image.open(image_path).convert("RGB").resize((IMG_SIZE, IMG_SIZE))
    img_array = np.array(img)
    img_array = tf.keras.applications.mobilenet_v2.preprocess_input(img_array)
    img_array = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_array)[0]
    class_index = np.argmax(prediction)
    label = class_names[class_index]

    confidence = prediction[class_index]

    recyclable = ["paper","plastic","metal","cardboard",
                  "brown-glass","green-glass","white-glass"]

    if confidence < 0.5:
        final_type = "Non-Recyclable"
        bin_type = "Reject Waste Bin"
    elif label in recyclable:
        final_type = "Recyclable"
        bin_type = "Dry Waste Bin"
    elif label == "biological":
        final_type = "Biodegradable"
        bin_type = "Wet Waste Bin"
    else:
        final_type = "Non-Recyclable"
        bin_type = "Reject Waste Bin"

    # ORIGINAL IMAGE
    with open(image_path, "rb") as f:
        img_data = base64.b64encode(f.read()).decode()
    img_src = f"data:image/jpeg;base64,{img_data}"

    # HEATMAP
    heatmap_src = generate_heatmap(image_path)

    # =========================
    # UI (UNCHANGED + HEATMAP ADDED)
    # =========================
    html = f"""
<style>
@import url('https://fonts.googleapis.com/css2?family=Great+Vibes&family=Inter:wght@300;400;600&display=swap');

body {{
    background: linear-gradient(180deg, #eef3ef, #e4ebe5);
    font-family: 'Inter', sans-serif;
    color: #2f3e34;
}}

.container {{
    width: 920px;
    margin: auto;
    padding-top: 40px;
    padding-bottom: 60px;
}}

.card {{
    background: #f8faf8;
    border-radius: 16px;
    padding: 30px;
    margin-bottom: 30px;
    box-shadow: 0 8px 25px rgba(0,0,0,0.05);
}}

.header {{
    display: flex;
    align-items: center;
    gap: 10px;
    margin-bottom: 10px;
}}

.title {{
    font-family: 'Great Vibes', cursive;
    font-size: 44px;
    color: #3a5a40;
}}

.icon {{
    font-size: 26px;
}}

.subtitle {{
    font-size: 12px;
    color: #7c8f80;
    margin-bottom: 20px;
}}

.top {{
    display: flex;
    align-items: center;
    gap: 40px;
}}

.image img {{
    width: 170px;
    border-radius: 12px;
}}

.info {{
    display: flex;
    flex-direction: column;
    gap: 16px;
    flex: 1;
}}

.row {{
    display: flex;
    flex-direction: column;
    gap: 4px;
}}

.label {{
    font-size: 11px;
    letter-spacing: 1px;
    color: #6b7d6d;
}}

.value {{
    font-size: 20px;
    font-weight: 600;
}}

.sub {{
    font-size: 13px;
    color: #7c8f80;
}}

.green {{ color: #3a7d44; }}
.yellow {{ color: #c9a227; }}
.red {{ color: #a65d57; }}

.pie-wrapper {{
    position: relative;
    width: 95px;
    height: 95px;
}}

.pie {{
    width: 100%;
    height: 100%;
    border-radius: 50%;
    background: conic-gradient(
        #588157 0% {round(confidence*100)}%,
        #dce5dc {round(confidence*100)}% 100%
    );
}}

.pie::after {{
    content: '';
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 75%;
    height: 75%;
    background: #f8faf8;
    border-radius: 50%;
}}

.pie-text {{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 13px;
    font-weight: 600;
}}

.desc {{
    margin-top: 25px;
    font-size: 13px;
    line-height: 1.6;
    color: #6b7d6d;
}}

.bottom {{
    display: flex;
    justify-content: space-between;
    margin-top: 20px;
    font-size: 12px;
    color: #7c8f80;
}}

.badge {{
    padding: 5px 12px;
    border-radius: 20px;
    background: #3a5a40;
    color: white;
}}

.heatmap-section {{
    margin-top: 18px;
    text-align: center;
}}

.heatmap-title {{
    font-size: 16px;
    font-weight: 600;
    color: #3a5a40;
    margin-bottom: 10px;
}}

.heatmap-img {{
    width: 320px;
    border-radius: 12px;
    box-shadow: 0 6px 20px rgba(0,0,0,0.08);
}}

.heatmap-desc {{
    margin-top: 12px;
    font-size: 13px;
    color: #6b7d6d;
    line-height: 1.6;
    max-width: 520px;
    margin-left: auto;
    margin-right: auto;
}}
</style>

<div class="container">
<div class="card">

<div class="header">
<div class="icon">♻️</div>
<div class="title">Waste Classification</div>
</div>

<div class="subtitle">
Smart eco-based waste analysis system
</div>

<div class="top">

<div class="image">
<img src="{img_src}">
</div>

<div class="info">

<div class="row">
<div class="label">PREDICTION</div>
<div class="value">{label.upper()}</div>
</div>

<div class="row">
<div class="label">CLASSIFICATION</div>
<div class="value {'yellow' if final_type.lower() == 'biodegradable' else 'green' if final_type.lower() == 'recyclable' else 'red'}">
{final_type.upper()}
</div>
<div class="sub">{bin_type}</div>
</div>

</div>

<div class="pie-wrapper">
<div class="pie"></div>
<div class="pie-text">{round(confidence*100)}%</div>
</div>

</div>

<div class="desc">
This system analyzes waste materials using visual patterns and texture recognition
to determine appropriate disposal methods, supporting efficient and eco-friendly waste management.
</div>

<div class="bottom">
<div>Eco-aware classification interface</div>
<div class="badge">MobileNetV2</div>
</div>

<div class="heatmap-section">
<div class="heatmap-title">Model Focus Regions</div>
<img src="{heatmap_src}" class="heatmap-img">

<div class="heatmap-desc">

    <b style="display:block; margin-bottom:10px;">Color Interpretation</b>

    <div style="display:flex; justify-content:center; gap:10px; flex-wrap:wrap; margin-bottom:12px;">

        <div style="
            background:#e6f4ea;
            color:#2f6f4f;
            padding:6px 12px;
            border-radius:20px;
            font-size:12px;">
            🔴 High Focus
        </div>

        <div style="
           background:#e6f4ea;
            color:#2f6f4f;
            padding:6px 12px;
            border-radius:20px;
            font-size:12px;">
            🟡 Medium Focus
        </div>

        <div style="
            background:#e6f4ea;
            color:#2f6f4f;
            padding:6px 12px;
            border-radius:20px;
            font-size:12px;">
            🔵 Low Focus
        </div>

    </div>

    The model analyzes texture, edges, and surface patterns of the object.
    Regions with stronger highlights contribute more to the prediction,
    while softer areas provide supporting context.

    <br><br>

    🌿 The highlighted regions reflect how the model visually understands and interprets the object during classification.

</div>

</div>

</div>
</div>
"""

    display(HTML(html))

# =========================
# RUN
# =========================
def test_image():
    uploaded = files.upload()
    for file in uploaded.keys():
        predict_waste(file)

test_image()